export default{
    entrar:'Entrar',
    cadastrar: 'Cadastrar',
    app_name:'Opus',
    lite:'Lite',
    email:'Email',
    hint_email:'aleksiam_gutenberg@opus.com',
    senha:'Senha',
    hint_senha:'***********',
    esqueceu_senha:'Esqueceu a senha ?',
    user:'Nome de usuario',
    hint_user:'Junior Gutenberg',
    hint_pedidos_search:'Pesquise pedidos recebidos: ',
    hint_enviados_search:'Pesquise o que você enviou: ',
    label_local:'Informe sua localização',
    label_filtro:'Limite de Busca',
    minha_loc:'Usar minha localização',
    label_manual:'Editar Manualmente',
    label_rua:'Rua',
    label_bairro:'Bairro',
    label_cidade:'Cidade',
    label_estado:'Estado',
    label_pais:'País',
    hint_rua:'Av Franz João Hassis',
    hint_bairro:'Santa Cruz',
    hint_cidade:'Volta Redonda',
    hint_estado:'Rio De Janeiro',
    hint_pais:'Brasil',
    btn_local:'Confirmar Localização',
    btn_radius:'Confirmar Distância'
}