import {StyleSheet} from 'react-native';
import color from '../../../res/values/colors'

const styles = StyleSheet.create({
    /**
         * Login Main
         */
    container:{
        flex:   1
    },

    image_login:{
        width:'100%',
        height:'100%'
    },
    background_login:{
        position:'absolute',
        width:'100%',
        height:'100%',
        backgroundColor: color.blur_fundo,
        opacity:0.68
    },
    button_login:{
        position:'absolute',
        height:55,
        width:'85%',
        alignSelf:'center',
        alignItems:'center',
        justifyContent:'center',
        borderColor:color.black,
        borderWidth:1,
        borderRadius:25,
        bottom:'25%'
    },
    text_button_login:{
        fontSize:18,
        color:color.black,
        fontWeight:'bold'
    },
    button_cadastro:{
        position:'absolute',
        height:55,
        width:'85%',
        alignSelf:'center',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:color.black,
        borderRadius:25,
        bottom:'15%'
    },
    text_button_cadastro:{
        fontSize:18,
        color:color.blur_fundo,
        fontWeight:'bold'
    },
    text_app:{
        position:'absolute',
        fontSize:24,
        color:color.black,
        letterSpacing:0,
        top:'40%',
        alignSelf:'center'
    },
    text_lite:{
        position:'absolute',
        fontSize:24,
        fontWeight:'bold',
        color:color.black,
        letterSpacing:0,
        top:'40%',
        alignSelf:'center'
    },
    icon:{
        position:'absolute',
        width:55,
        height:55,
        alignSelf:'center',
        top:'32%'
    },
    /**
     * Entrar
     */
     container_entrar:{
        flex:   1,
        backgroundColor:color.cinza
    },
     text_email:{
        position:'absolute',
        fontSize:16,
        fontWeight:'bold',
        color:color.blur_fundo,
        letterSpacing:0,
        top:'30%',
        start:'10%'
    },
    text_input_email:{
        position:'absolute',
        fontSize:16,
        color:color.blur_fundo,
        width:'80%',
        top:'35%',
        start:'10%',
        borderBottomColor:color.blur_fundo,
        borderBottomWidth:0.5,
        paddingBottom:8
    },
    text_password:{
        position:'absolute',
        fontSize:16,
        fontWeight:'bold',
        color:color.blur_fundo,
        letterSpacing:0,
        top:'42%',
        start:'10%'
    },
    text_input_password:{
        position:'absolute',
        fontSize:16,
        color:color.blur_fundo,
        width:'80%',
        top:'47%',
        start:'10%',
        borderBottomColor:color.blur_fundo,
        borderBottomWidth:0.5,
        paddingBottom:8
    }, 
    button_login_entrar:{
        position:'absolute',
        height:55,
        width:'85%',
        alignSelf:'center',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:color.blur_fundo,
        borderRadius:25,
        bottom:'28%'
    },
    text_esqueceu:{
        position:'absolute',
        fontSize:14,
        fontStyle:'italic',
        fontWeight:'bold',
        color:color.blur_fundo,
        letterSpacing:0,
        bottom:'45%',
        end:'10%'
    },  
    icon_amarelo:{
        position:'absolute',
        width:45,
        height:45,
        alignSelf:'center',
        top:'18%'
    },
    button_back:{
        position:'absolute',
        start:'5%',
        top:'10%'
    },
    /**
     * Cadastro
     */

     text_input_confirm_password:{
        position:'absolute',
        fontSize:16,
        color:color.blur_fundo,
        width:'80%',
        top:'59%',
        start:'10%',
        borderBottomColor:color.blur_fundo,
        borderBottomWidth:0.5,
        paddingBottom:8
    },
    text_confirm_password:{
        position:'absolute',
        fontSize:16,
        fontWeight:'bold',
        color:color.blur_fundo,
        letterSpacing:0,
        top:'54%',
        start:'10%'
    },
    button_login_cadastrar:{
        position:'absolute',
        height:55,
        width:'85%',
        alignSelf:'center',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:color.blur_fundo,
        borderRadius:25,
        bottom:'18%'
    }
})

export {styles}