import {StyleSheet} from 'react-native';
import color from '../../../res/values/colors'

const styles = StyleSheet.create({
    /**
         * Login Main
         */
    container:{
        flex:   1,
        backgroundColor:color.cinza
    },
    image_fundo:{
        position:'absolute',
        width:"100%",
        height:"25%"
    },
    fundo_curvada:{
        position:'absolute',
        width:"100%",
        height:"100%",
        top:160,
        borderRadius:30,
        zIndex:5,
        backgroundColor:color.cinza
    },
    fundo_localizacao:{
        position:'absolute',
        backgroundColor:color.blur_fundo,
        borderRadius:20,
        height:50,
        width:'90%',
        top:60,
        alignSelf:'center',
        alignItems:'center',
        zIndex:5
    },
    icon_localizacao:{
        alignSelf:'flex-start',
        top:10,
        marginLeft:15
    },
    text_localizacao:{
        fontSize:16,
        alignSelf:'center',
        textAlign:'center',
        maxWidth:'82%',
        alignContent:'center',
        bottom:12,
        marginStart:25
    },
    button_add:{
        position:'absolute',
        width:60,
        height:60, 
        backgroundColor:color.blur_fundo, 
        alignItems:'center', 
        justifyContent:'center',
        borderRadius:30, 
        right:25,
        bottom:25, 
        elevation:7, 
        zIndex:9
    },
    icon_localizacao_distancia:{
        position:'absolute',
        alignSelf:'flex-start',
        top:125,
        start:35
    },
    text_localizacao_distancia:{
        position:'absolute',
        alignSelf:'flex-start',
        top:130,
        start:65,
        maxWidth:'82%',
        color:color.white,
        fontSize:17
    },
    btn_add_float:{
        position:'absolute',
        width:60, 
        height:60, 
        backgroundColor:color.blur_fundo, 
        alignItems:'center', 
        justifyContent:'center',
        borderRadius:30, 
        right:25,
        bottom:125, 
        elevation:7, 
        zIndex:9
    },
    container_flat:{
        top:20,
        start:10,
        end:10
    },
    container_list:{
        position:'absolute',
        elevation:1.5,
        width:'95%',
        height:200
    },
    back_list:{
        position:'absolute',
        width:'100%',
        height:'100%',
        borderRadius:25,
        backgroundColor:color.cinza_dark,
        elevation:5,
        zIndex:15,
        borderStartWidth:3,
        borderStartColor:color.blur_fundo,
        borderEndWidth:0.5,
        borderBottomColor:color.black
    },
    icon_wallet:{
        position:'absolute',
        bottom:25,
        start:25
    },
    text_title:{
        position:'absolute',
        fontSize:20,
        alignSelf:'flex-start',
        maxWidth:'90%',
        top:25,
        marginStart:25,
        color:color.white,
        fontWeight:'bold'
    },
    text_desc:{
        position:'absolute',
        fontSize:18,
        alignSelf:'flex-start',
        maxWidth:'90%',
        top:55,
        marginStart:25,
        color:color.white,
        fontWeight:'normal'
    },
    text_price:{
        position:'absolute',
        fontSize:22,
        alignSelf:'flex-start',
        maxWidth:'90%',
        bottom:28,
        start:60,
        color:color.white,
        fontWeight:'bold'
    },
    label_local:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        alignSelf:'center',
        top:110,
        fontWeight:'bold'
    },
    icon_back:{
        position:'absolute',
        top:70,
        start:'5%'
    },
    container_minha_loc:{
        position:'absolute',
        top:180,
        width:'100%'
    },
    icon_loc:{
        position:'absolute',
        start:'8%'
    },
    text_usar_loc:{
        position:'absolute',
        fontSize:16,
        top:4,
        alignSelf:'flex-start',
        start:'20%',
        color:color.white,
        fontWeight:'bold',
        color:color.blur_fundo
    },
    label_manual:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        alignSelf:'center',
        top:250,
        fontWeight:'bold'
    },
    label_rua:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        start:'10%',
        alignSelf:'flex-start',
        top:290,
        fontWeight:'normal'
    },
    fundo_rua:{
        position:'absolute',
        width:'90%',
        alignSelf:'center',
        height:40,
        top:320,
        borderWidth:2,
        borderColor:color.cinza_dark,
        borderRadius:10
    },
    input_rua:{
        position:'absolute',
        fontSize:18,
        width:'90%',
        color:color.white,
        top:7,
        start:15
    },
    label_bairro:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        start:'10%',
        alignSelf:'flex-start',
        top:380,
        fontWeight:'normal'
    },
    fundo_bairro:{
        position:'absolute',
        width:'90%',
        alignSelf:'center',
        height:40,
        top:410,
        borderWidth:2,
        borderColor:color.cinza_dark,
        borderRadius:10
    },
    label_cidade:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        start:'10%',
        alignSelf:'flex-start',
        top:470,
        fontWeight:'normal'
    },
    fundo_cidade:{
        position:'absolute',
        width:'90%',
        alignSelf:'center',
        height:40,
        top:500,
        borderWidth:2,
        borderColor:color.cinza_dark,
        borderRadius:10
    },
    label_estado:{
        position:'absolute',
        fontSize:18,
        color:color.white,
        start:'10%',
        alignSelf:'flex-start',
        top:560,
        fontWeight:'normal'
    },
    fundo_estado:{
        position:'absolute',
        width:'90%',
        alignSelf:'center',
        height:40,
        top:590,
        borderWidth:2,
        borderColor:color.cinza_dark,
        borderRadius:10
    },
    container_button:{
        position:'absolute',
        top:690,
        backgroundColor:color.blur_fundo,
        width:'90%',
        height:50,
        alignSelf:'center',
        justifyContent:'center',
        borderRadius:10
    },
    text_button:{
        position:'absolute',
        alignSelf:'center',
        fontSize:20,
        color:color.black,
        fontWeight:'bold'
    },
    slider:{
        position:'absolute',
        top:200,
        width:'90%',
        alignSelf:'center'
    },
    label_min_slider:{
        position:'absolute',
        fontWeight:'bold',
        color:color.white,
        top:240,
        fontSize:18,
        start:25
    },
    label_max_slider:{
        position:'absolute',
        fontWeight:'bold',
        color:color.white,
        top:240,
        fontSize:18,
        end:25
    }
})

export {styles}