import {StyleSheet} from 'react-native';
import color from '../../../res/values/colors'

const styles = StyleSheet.create({
    /**
         * Login Main
         */
    container:{
        flex:   1,
        backgroundColor:color.cinza
    },
    image_fundo:{
        position:'absolute',
        width:"100%",
        height:"25%"
    },
    fundo_curvada:{
        position:'absolute',
        width:"100%",
        height:"100%",
        top:160,
        borderRadius:30,
        zIndex:5,
        backgroundColor:color.cinza
    },
    fundo_search:{
        position:'absolute',
        backgroundColor:color.blur_fundo,
        borderRadius:20,
        height:50,
        width:'90%',
        top:60,
        alignSelf:'center',
        alignItems:'center',
        zIndex:5
    },
    icon_search:{
        position:'absolute',
        alignSelf:'flex-end',
        bottom:10,
        end:15
    },
    text_input_search:{
        position:'absolute',
        fontSize:20,
        color:color.black,
        width:'80%',
        top:10,
        start:15,
        borderBottomColor:color.black,
        borderBottomWidth:0.5
    },
    button_add:{
        position:'absolute',
        width:60,
        height:60, 
        backgroundColor:color.blur_fundo, 
        alignItems:'center', 
        justifyContent:'center',
        borderRadius:30, 
        right:25,
        bottom:25, 
        elevation:7, 
        zIndex:9
    },
    icon_localizacao_distancia:{
        position:'absolute',
        alignSelf:'flex-start',
        top:125,
        start:35
    },
    text_localizacao_distancia:{
        position:'absolute',
        alignSelf:'flex-start',
        top:130,
        start:65,
        maxWidth:'82%',
        color:color.white,
        fontSize:17
    },
    btn_add_float:{
        position:'absolute',
        width:60, 
        height:60, 
        backgroundColor:color.blur_fundo, 
        alignItems:'center', 
        justifyContent:'center',
        borderRadius:30, 
        right:25,
        bottom:125, 
        elevation:7, 
        zIndex:9
    },
    container_flat:{
        top:20,
        start:10,
        end:10
    },
    container_list:{
        position:'absolute',
        elevation:1.5,
        width:'95%',
        height:200
    },
    back_list:{
        position:'absolute',
        width:'100%',
        height:'100%',
        borderRadius:25,
        backgroundColor:color.cinza_dark,
        elevation:5,
        zIndex:15,
        borderStartWidth:3,
        borderStartColor:color.blur_fundo,
        borderEndWidth:0.5,
        borderBottomColor:color.black
    },
    icon_wallet:{
        position:'absolute',
        bottom:25,
        start:25
    },
    text_title:{
        position:'absolute',
        fontSize:20,
        alignSelf:'flex-start',
        maxWidth:'90%',
        top:25,
        marginStart:25,
        color:color.white,
        fontWeight:'bold'
    },
    text_desc:{
        position:'absolute',
        fontSize:18,
        alignSelf:'flex-start',
        maxWidth:'90%',
        top:55,
        marginStart:25,
        color:color.white,
        fontWeight:'normal'
    },
    text_price:{
        position:'absolute',
        fontSize:22,
        alignSelf:'flex-start',
        maxWidth:'90%',
        bottom:28,
        start:60,
        color:color.white,
        fontWeight:'bold'
    }
})

export {styles}